%YAML:1.0

#common parameters
imu_topic: "/IMU_data"
image_topic: "/cv/ipcam/image_raw"
output_path: "/home/touchair/output/"

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 1920
image_height: 1080
distortion_parameters:
   k1: 0.07191433407098516
   k2: -0.050426580100147424
   p1: 0.0007377056222214622
   p2: 0.0007067050708822046
projection_parameters:
   fx: 397.14667678829426
   fy: 398.8331103148402
   cx: 308.2878001257402
   cy: 225.7727691949205

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.00738892, -0.9992197, 0.03879944,
          -0.99965707, -0.00640623, 0.02539103,
          -0.02512266,  -0.03897374, -0.99892437]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.00170814, 0.00781076, -0.05943583]

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.010667774076        # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.000812916386142         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.000724013511762         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 6.70203756906e-05       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.8033172      # gravity magnitude

#loop closure parameters
loop_closure: 1                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0             # useful in real-time and large project
pose_graph_save_path: "/home/touchair/output/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: -0.0415556196774                  # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ
